INSERT INTO public.objection_responses (category, title, response_text, tone, compliance_status, is_published, sort_order)
VALUES
('price', 'Compare the daily cost', 'I understand that it can feel like a big number upfront. What helped me was breaking it down into a daily habit and comparing it with things I was already spending on. For me, it became less about buying a product and more about choosing to support my routine consistently.', 'logical', 'passed', true, 1),
('price', 'Start small', 'That is a fair concern, and I would never want you to feel pressured. If you are curious, we can look at the smallest option first so you can see whether it fits your lifestyle. I prefer people make calm decisions instead of feeling pushed.', 'empathetic', 'passed', true, 2),
('price', 'My own value check', 'I had the same hesitation at first. In my experience, the value came from having a simple routine I could actually follow. I cannot decide for you, but I can share what I use and why it made sense for me personally.', 'story', 'passed', true, 3),
('skepticism', 'Healthy skepticism is fair', 'I get why you would ask that. I was cautious too, because I do not like overhyped promises. What helped me was trying a simple routine, paying attention to how I felt day to day, and deciding based on my own experience rather than someone else pressuring me.', 'empathetic', 'passed', true, 1),
('skepticism', 'Routine over magic', 'I do not see this as a magic fix. For me, it works best as part of normal choices like better meals, water, movement, and consistency. If you ever try it, I would suggest looking at it as support for a routine, not a shortcut.', 'logical', 'passed', true, 2),
('skepticism', 'Past experience matters', 'I understand if you tried supplements before and felt disappointed. I would feel cautious too. My approach is simply to share what I personally do, answer questions honestly, and let you decide whether it is worth exploring again.', 'story', 'passed', true, 3),
('mlm_concern', 'Clear and honest business model', 'That is a fair question. Yes, Herbalife uses independent distributors, and I believe it is important to be upfront about that. For me, the focus is helping people choose products they actually want, not pressuring anyone into something that does not fit.', 'logical', 'passed', true, 1),
('mlm_concern', 'No pressure to join', 'I hear you. Some people have had uncomfortable experiences with direct selling, and I do not want to be that person. You do not need to join anything to ask questions or try a product. I am happy to keep it simple and transparent.', 'empathetic', 'passed', true, 2),
('mlm_concern', 'My personal boundary', 'When I started, I decided I would only share in a way that felt respectful. That means no chasing, no pressure, and no big promises. If someone is interested, I explain clearly. If not, I still value the relationship.', 'story', 'passed', true, 3),
('time', 'Keep it simple', 'I understand being busy. That is exactly why I like simple routines rather than complicated plans. If something takes too much effort, most of us will not keep doing it. We can look at what fits into your current day instead of adding pressure.', 'logical', 'passed', true, 1),
('time', 'No big commitment', 'That makes sense. You do not need to overhaul your whole schedule. Sometimes the best starting point is one small habit that fits into breakfast, work, or after exercise. If now is not the right time, that is okay too.', 'empathetic', 'passed', true, 2),
('time', 'My busy-day approach', 'I used to think I needed a perfect routine before starting. What helped me was choosing something simple enough for busy days. In my experience, consistency became easier when I stopped making it complicated.', 'story', 'passed', true, 3),
('loyalty', 'Respect what works', 'That is great. If you already have something you enjoy and it works for your lifestyle, I respect that. I am not here to pull you away from it. I can simply share what I use, and you can compare calmly if you are ever curious.', 'empathetic', 'passed', true, 1),
('loyalty', 'Compare without pressure', 'There is no need to switch just because I use something different. If you ever want to compare ingredients, convenience, or how each option fits your routine, I am happy to talk through it without pressure.', 'logical', 'passed', true, 2),
('loyalty', 'Why I chose this', 'I had brands I liked before too. What changed for me was finding a routine that felt easy to repeat and having support around it. That may or may not matter to you, but I am happy to share why I chose this path.', 'story', 'passed', true, 3)
ON CONFLICT DO NOTHING;
